name: Tests

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Go tests on ${{ matrix.name }}
    # Only run this matrix leg if its libray exists
    if: ${{ hashFiles(matrix.lib_glob) != '' || hashFiles(matrix.fallback_glob) != '' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux_amd64
            os: ubuntu-latest
            lib_glob: bindings/go/libs/linux_amd64/lib_turso_go.so
            fallback_glob: libs/linux_amd64/lib_turso_go.so
          - name: linux_arm64
            os: ubuntu-24.04-arm64
            lib_glob: bindings/go/libs/linux_arm64/lib_turso_go.so
            fallback_glob: libs/linux_arm64/lib_turso_go.so
          - name: macos_amd64
            os: macos-13
            lib_glob: bindings/go/libs/darwin_amd64/lib_turso_go.dylib
            fallback_glob: libs/darwin_amd64/lib_turso_go.dylib
          - name: macos_arm64
            os: macos-14
            lib_glob: bindings/go/libs/darwin_arm64/lib_turso_go.dylib
            fallback_glob: libs/darwin_arm64/lib_turso_go.dylib
          - name: windows_amd64
            os: windows-latest
            lib_glob: bindings/go/libs/windows_amd64/lib_turso_go.dll
            fallback_glob: libs/windows_amd64/lib_turso_go.dll

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          check-latest: true

      - name: Run Go tests
        run: go test -v ./...
